plugins {
    id 'java'
}

group = 'com.zhoufz'
version = '5.2.15.RELEASE'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(path: ':spring-context')
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}